version: "2"
networks:
  albathanext:
    driver: bridge

services:
  mysqlhost:
    container_name: mysqlhost
    image: mysql
    cap_add:
      - SYS_NICE
    security_opt:
      - seccomp:unconfined
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: albathanext
      MYSQL_ROOT_HOST: '%'
    ports:
      - '3306:3306'
#    volumes:
#      - '~/dev/dbs-data/mysql:/var/lib/mysql'
    expose:
      - 3306
    networks:
      - albathanext

  albathanext:
    container_name: albathanext
    build:
      context: .
    image: adoptopenjdk/openjdk11
    restart: 'no'
    ports:
      - "80:8080"
    networks:
      - albathanext
    depends_on:
      - mysqlhost
